spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ewm-db:5432/ewmdb
    username: ewmuser
    password: ewmpass
  sql:
    init:
      mode: always
stats-server:
  uri: http://stats-server:9090