package ru.practicum.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.FieldDefaults;

import java.time.LocalDateTime;

/**
 * Entity representing a recorded endpoint hit in the system.
 *
 * Fields:
 * - `id` – Unique identifier of the hit record. Auto-generated by database.
 * - `app` – Name of the application recording the request.
 * - `uri` – Requested URI path (max length: 2083 chars).
 * - `ip` – IP address from which the request originated (max length: 31 chars).
 * - `timestamp` – Date and time of the recorded request.
 */
@Entity
@Getter
@Setter
@ToString
@Table(name = "hits")
@FieldDefaults(level = AccessLevel.PRIVATE)
public class Hit {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Long id;
    String app;
    String uri;
    String ip;
    LocalDateTime timestamp;
}
