services:
  discovery-server:
    build:
      context: infra/discovery-server
      dockerfile: Dockerfile
    image: discovery-server-image
    container_name: discovery-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - ewm-network

  config-server:
    build:
      context: infra/config-server
      dockerfile: Dockerfile
    image: config-server-image
    container_name: config-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discovery-server:8761/eureka/apps/config-server"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 30s
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    networks:
      - ewm-network

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=statspass
      - POSTGRES_USER=statsuser
      - POSTGRES_DB=statsdb
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - ewm-network

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_PASSWORD=ewmpass
      - POSTGRES_USER=ewmuser
      - POSTGRES_DB=ewmdb
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - ewm-network

  stats-server:
    build:
      context: stats/stats-server
      dockerfile: Dockerfile
    image: stats-server-image
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      config-server:
        condition: service_healthy
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - SPRING_DATASOURCE_USERNAME=statsuser
      - SPRING_DATASOURCE_PASSWORD=statspass
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discovery-server:8761/eureka/apps/stats-server"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
    networks:
      - ewm-network

  ewm-service:
    build:
      context: core/main-service
      dockerfile: Dockerfile
    image: ewm-service-image
    container_name: ewm-service
    depends_on:
      config-server:
        condition: service_healthy
      ewm-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb
      - SPRING_DATASOURCE_USERNAME=ewmuser
      - SPRING_DATASOURCE_PASSWORD=ewmpass
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discovery-server:8761/eureka/apps/main-service"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
    networks:
      - ewm-network

  gateway-server:
    build:
      context: infra/gateway-server
      dockerfile: Dockerfile
    image: gateway-server-image
    container_name: gateway-server
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
    networks:
      - ewm-network

networks:
  ewm-network:
    driver: bridge