services:
  discovery-server:
    build:
      context: infra/discovery-server
      dockerfile: Dockerfile
    image: discovery-server-image
    container_name: discovery-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - ewm-network

  config-server:
    build:
      context: infra/config-server
      dockerfile: Dockerfile
    image: config-server-image
    container_name: config-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://discovery-server:8761/eureka/apps/config-server" ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 30s
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    networks:
      - ewm-network

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=statspass
      - POSTGRES_USER=statsuser
      - POSTGRES_DB=statsdb
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - ewm-network

  stats-server:
    build:
      context: stats/stats-server
      dockerfile: Dockerfile
    image: stats-server-image
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      config-server:
        condition: service_healthy
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - SPRING_DATASOURCE_USERNAME=statsuser
      - SPRING_DATASOURCE_PASSWORD=statspass
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://discovery-server:8761/eureka/apps/stats-server" ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
    networks:
      - ewm-network

  gateway-server:
    build:
      context: infra/gateway-server
      dockerfile: Dockerfile
    image: gateway-server-image
    container_name: gateway-server
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
    networks:
      - ewm-network

  user-service:
    build: core/user-service
    container_name: user-service
    depends_on:
      user-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      stats-server:
        condition: service_healthy
    networks:
      - ewm-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/userdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8083
    healthcheck:
      test: "curl --fail --silent localhost:8083/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 25s
      retries: 10

  user-db:
    image: postgres:16.1
    container_name: postgres-user-db
    networks:
      - ewm-network
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=userdb
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  subscription-service:
    build: core/subscription-service
    container_name: subscription-service
    depends_on:
      user-db:
        condition: service_healthy
      subscription-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      stats-server:
        condition: service_healthy
      user-service:
        condition: service_healthy
    networks:
      - ewm-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://subscription-db:5432/subscriptiondb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8084
    healthcheck:
      test: "curl --fail --silent localhost:8084/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 25s
      retries: 10

  subscription-db:
    image: postgres:16.1
    container_name: postgres-subscription-db
    networks:
      - ewm-network
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=subscriptiondb
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  request-service:
    build: core/request-service
    container_name: request-service
    depends_on:
      user-db:
        condition: service_healthy
      subscription-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      stats-server:
        condition: service_healthy
      user-service:
        condition: service_healthy
      request-db:
        condition: service_healthy
    networks:
      - ewm-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://request-db:5432/requestdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8085
    healthcheck:
      test: "curl --fail --silent localhost:8085/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 25s
      retries: 10

  request-db:
    image: postgres:16.1
    container_name: postgres-request-db
    networks:
      - ewm-network
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=requestdb
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  event-service-db:
    image: postgres:16.1
    container_name: postgres-event-service-db
    networks:
      - ewm-network
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=eventdb
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  event-service:
    build: core/event-service
    container_name: ewm-event-service
    depends_on:
      user-db:
        condition: service_healthy
      subscription-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      stats-server:
        condition: service_healthy
      user-service:
        condition: service_healthy
      request-db:
        condition: service_healthy
      event-service-db:
        condition: service_healthy
    networks:
      - ewm-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://event-service-db:5432/eventdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8086
    healthcheck:
      test: "curl --fail --silent localhost:8086/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 25s
      retries: 10

networks:
  ewm-network:
    driver: bridge