spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://user-db:5432/userdb
    username: root
    password: root
  sql:
    init:
      mode: always
stat-server:
  uri: http://stats-server:9090