spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ewm_service_route
          uri: lb://main-service
          predicates:
            - Path=/admin/**,/categories/**,/compilations/**,/events/**,/users/**,/requests/**,/subscriptions/**,/subscribers/**
server:
  port: 8080