spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6432/subscriptiondb
    username: root
    password: root
  sql:
    init:
      mode: always

server:
  port: 0